server:
  port: 8000
spring:
  application:
    name: warehouse
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${wh.db.host}:3306/warehouse?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${wh.db.pw}
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123321
      database: 6
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  rabbitmq:
    host: 192.168.100.128
    port: 5672
    username: warehouse
    password: 123321
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-retries: 3
        default-requeue-rejected: false
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-retries: 3
      publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
      publisher-returns: true # 开启publisher return机制
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.zh: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"



wh:
  jwt:
    location: classpath:wh.jks
    alias: wh
    password: 123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi